### ISSUE TITLE
 Sourcemap is not generated

### ISSUE THREAD

**Issue by psamim** [angular-microfrontends/play#1] opened 2021-06-07 09:04 UTC
Hi,

It is the same issue as https://github.com/angular-microfrontends/navbar/issues/1

By enabling source maps, no actual source map is generated.

Thanks

**Comment by internettrans** [comment] 2021-06-07 17:50
Closing as duplicate of https://github.com/angular-microfrontends/navbar/issues/1

**Closed as completed by internettrans** 2021-06-07 17:50 UTC
